### ISSUE TITLE
Presentation: Feature Roadmap + Recap Initial Presentation

### ISSUE THREAD

**Issue by Alorcus** [hpi-swt2/bookkeeper-portal-red#330]
Things which can be named:
* Small Recap: Where did we start?
* Where are we currently?
* What are possible feature for the future? E.g.
    * Analytics
    * Wish list
    * normal registration (not only OICD)  
    
Kickoff:
![grafik](https://user-images.githubusercontent.com/63072611/214014930-6f6d3656-1c63-4661-b791-9a2cd114dfb5.png)
Interim Presentation:
![grafik](https://user-images.githubusercontent.com/63072611/214014748-bc04fa01-b76b-4f2a-bd83-ae98a6ce9b1c.png)

Resources
- Kickoff https://docs.google.com/presentation/d/13avoiOdKkljzHqLiNbx37NUXFuuYJwTI/edit#slide=id.g18ba7328ecf_0_325
- Interim https://docs.google.com/presentation/d/1spYzYFtR0W_4Dqrkd-UvjXvcLiHzd_KAoHqNwwfrme4/edit#slide=id.g1bf707cb8ee_1_171
- Final https://docs.google.com/presentation/d/1IjyQyxHPuxxQxzlfFi0tAFhfKYm5mUNT3IAWK_PsX60/edit#slide=id.g1af1a4d2422_1_2

### Acceptance Criteria

- [ ] 3 minutes of content
- [ ] 1 person presenting (this person also presents Project objective)
- [ ] contact me or another PO if you have any questions :)
