### ISSUE TITLE
Add Return Process: Owner Checklist

### ISSUE THREAD

**Issue by DefineDan** [hpi-swt2/bookkeeper-portal-red#39]
As an asset owner, I want to be able to fill out a checklist after an asset is returned. Only after I do this, the item is available again. This helps me keep track of the assets condition.

### Dependencies
- #8 
- #37 

### Definition of Done:
- [ ] Option to create a custom checklist for every asset
- [ ] Integration into Return Owner Check process
- [ ] Checklist that can be filled out
